name: Run Examples

on:
  push:

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - 01-basic
          - 02-hooks
          - 03-matchers
          - 04-snapshots
          - 05-mocking-and-imports
          - 06-skips
          - 07-fuzzing
          - 07-web

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Wasmtime
        uses: jcbhmr/setup-wasmtime@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install root dependencies
        run: bun install

      - name: Build CLI and transform
        run: bun run build:cli && bun run build:transform

      - name: Install example dependencies
        working-directory: examples/${{ matrix.example }}
        run: bun install

      - name: Install Chromium for web example
        if: matrix.example == '07-web'
        run: npx -y playwright@latest install --with-deps chromium

      - name: Run example tests
        working-directory: examples/${{ matrix.example }}
        run: bun run test
